language: swift
osx_image: xcode12

install: true

env:
  global:
  - PROJECT=Brooklyn.xcodeproj
  - SCHEME=Brooklyn

script:
 - set -o pipefail
 - xcodebuild -project $PROJECT clean -scheme "$SCHEME"
 - xcodebuild -project $PROJECT build -scheme "$SCHEME"
