language: swift
osx_image: xcode10

install: true

env:
  global:
  - WORKSPACE=Brooklyn.xcworkspace
  - SCHEME=Brooklyn

script:
 - set -o pipefail
 - xcodebuild -workspace $WORKSPACE clean -scheme "$SCHEME"
 - xcodebuild -workspace $WORKSPACE build -scheme "$SCHEME"
